services:
  db:
    container_name: "blog-mysql_try"
    image: mysql:8.0.34
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blog
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes: 
      - ./mysql/sql:/docker-entrypoint-initdb.d
      - ./mysql/db/my.cnf:/etc/mysql/conf.d/my.cnf
  # redis:
  #   container_name: 'base_web_redis'
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
  
  # frontend:
  #   container_name: "blog-frontend"
  #   build:
  #     context: frontend
  #     dockerfile: ./Dockerfile
  #   volumes:
  #   - type: bind
  #     source: ./frontend/app
  #     target: /usr/src/app
  #   ports:
  #     - 3000:3000
  #   stdin_open: true
  #   # networks:
  #   #   - external.group
  #   #   - default

  backend_try:
    container_name: "backend_try"
    build:
      context: backend
      dockerfile: ./Dockerfile
    volumes:
    - type: bind
      source: ./backend/app
      target: /code
    ports:
      - 8000:8000
    stdin_open: true #標準入力をコンテナと紐付ける
    depends_on:
      - db
    # networks:
    #   - external.group
    #   - default

# networks:
#   external.group:
#     external: true